# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(785, 607)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupCom = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCom.sizePolicy().hasHeightForWidth())
        self.groupCom.setSizePolicy(sizePolicy)
        self.groupCom.setObjectName(_fromUtf8("groupCom"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupCom)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lbSerialTitle = QtGui.QLabel(self.groupCom)
        self.lbSerialTitle.setObjectName(_fromUtf8("lbSerialTitle"))
        self.verticalLayout_4.addWidget(self.lbSerialTitle)
        self.cbSerialPorts = QtGui.QComboBox(self.groupCom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSerialPorts.sizePolicy().hasHeightForWidth())
        self.cbSerialPorts.setSizePolicy(sizePolicy)
        self.cbSerialPorts.setObjectName(_fromUtf8("cbSerialPorts"))
        self.verticalLayout_4.addWidget(self.cbSerialPorts)
        self.btnConnectDisconnect = QtGui.QPushButton(self.groupCom)
        self.btnConnectDisconnect.setObjectName(_fromUtf8("btnConnectDisconnect"))
        self.verticalLayout_4.addWidget(self.btnConnectDisconnect)
        self.btnStartStop = QtGui.QPushButton(self.groupCom)
        self.btnStartStop.setObjectName(_fromUtf8("btnStartStop"))
        self.verticalLayout_4.addWidget(self.btnStartStop)
        self.groupPotenciometro = QtGui.QGroupBox(self.groupCom)
        self.groupPotenciometro.setObjectName(_fromUtf8("groupPotenciometro"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupPotenciometro)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbTitleValorLido = QtGui.QLabel(self.groupPotenciometro)
        self.lbTitleValorLido.setObjectName(_fromUtf8("lbTitleValorLido"))
        self.verticalLayout_2.addWidget(self.lbTitleValorLido)
        self.dialValorLido = QtGui.QDial(self.groupPotenciometro)
        self.dialValorLido.setMaximum(330)
        self.dialValorLido.setProperty("value", 0)
        self.dialValorLido.setObjectName(_fromUtf8("dialValorLido"))
        self.verticalLayout_2.addWidget(self.dialValorLido)
        self.sliderValorLido = QtGui.QSlider(self.groupPotenciometro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderValorLido.sizePolicy().hasHeightForWidth())
        self.sliderValorLido.setSizePolicy(sizePolicy)
        self.sliderValorLido.setMaximum(330)
        self.sliderValorLido.setOrientation(QtCore.Qt.Horizontal)
        self.sliderValorLido.setObjectName(_fromUtf8("sliderValorLido"))
        self.verticalLayout_2.addWidget(self.sliderValorLido)
        self.verticalLayout_4.addWidget(self.groupPotenciometro)
        self.groupLimiares = QtGui.QGroupBox(self.groupCom)
        self.groupLimiares.setObjectName(_fromUtf8("groupLimiares"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupLimiares)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelLimiar1 = QtGui.QLabel(self.groupLimiares)
        self.labelLimiar1.setObjectName(_fromUtf8("labelLimiar1"))
        self.verticalLayout.addWidget(self.labelLimiar1)
        self.sliderLimiar1 = QtGui.QSlider(self.groupLimiares)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderLimiar1.sizePolicy().hasHeightForWidth())
        self.sliderLimiar1.setSizePolicy(sizePolicy)
        self.sliderLimiar1.setMaximum(330)
        self.sliderLimiar1.setProperty("value", 100)
        self.sliderLimiar1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLimiar1.setObjectName(_fromUtf8("sliderLimiar1"))
        self.verticalLayout.addWidget(self.sliderLimiar1)
        self.labelLimiar2 = QtGui.QLabel(self.groupLimiares)
        self.labelLimiar2.setObjectName(_fromUtf8("labelLimiar2"))
        self.verticalLayout.addWidget(self.labelLimiar2)
        self.sliderLimiar2 = QtGui.QSlider(self.groupLimiares)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderLimiar2.sizePolicy().hasHeightForWidth())
        self.sliderLimiar2.setSizePolicy(sizePolicy)
        self.sliderLimiar2.setMaximum(330)
        self.sliderLimiar2.setProperty("value", 200)
        self.sliderLimiar2.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLimiar2.setObjectName(_fromUtf8("sliderLimiar2"))
        self.verticalLayout.addWidget(self.sliderLimiar2)
        self.labelLimiar3 = QtGui.QLabel(self.groupLimiares)
        self.labelLimiar3.setObjectName(_fromUtf8("labelLimiar3"))
        self.verticalLayout.addWidget(self.labelLimiar3)
        self.sliderLimiar3 = QtGui.QSlider(self.groupLimiares)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderLimiar3.sizePolicy().hasHeightForWidth())
        self.sliderLimiar3.setSizePolicy(sizePolicy)
        self.sliderLimiar3.setMaximum(330)
        self.sliderLimiar3.setProperty("value", 300)
        self.sliderLimiar3.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLimiar3.setObjectName(_fromUtf8("sliderLimiar3"))
        self.verticalLayout.addWidget(self.sliderLimiar3)
        self.verticalLayout_4.addWidget(self.groupLimiares)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupCom)
        self.verticalLayoutGrafico = QtGui.QVBoxLayout()
        self.verticalLayoutGrafico.setObjectName(_fromUtf8("verticalLayoutGrafico"))
        self.labelTitleLeds = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitleLeds.setFont(font)
        self.labelTitleLeds.setObjectName(_fromUtf8("labelTitleLeds"))
        self.verticalLayoutGrafico.addWidget(self.labelTitleLeds)
        self.graphicsLeds = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsLeds.setObjectName(_fromUtf8("graphicsLeds"))
        self.verticalLayoutGrafico.addWidget(self.graphicsLeds)
        self.horizontalLayout_2.addLayout(self.verticalLayoutGrafico)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Segunda Aula Prática de SEB", None))
        self.groupCom.setTitle(_translate("MainWindow", "Comunicação:", None))
        self.lbSerialTitle.setText(_translate("MainWindow", "Selecione a Porta Serial:", None))
        self.btnConnectDisconnect.setText(_translate("MainWindow", "Conectar", None))
        self.btnStartStop.setText(_translate("MainWindow", "Iniciar", None))
        self.groupPotenciometro.setTitle(_translate("MainWindow", "Potenciômetro", None))
        self.lbTitleValorLido.setText(_translate("MainWindow", "Valor Lido: 0.00 V", None))
        self.groupLimiares.setTitle(_translate("MainWindow", "Limiares:", None))
        self.labelLimiar1.setText(_translate("MainWindow", "Limiar 1: 1.00V", None))
        self.labelLimiar2.setText(_translate("MainWindow", "Limiar 2: 2.00V", None))
        self.labelLimiar3.setText(_translate("MainWindow", "Limiar 3: 3.00V", None))
        self.labelTitleLeds.setText(_translate("MainWindow", "Leds:", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

